import type { RunView } from "../../../services/discovery/src/types.ts";

export function RunProgress({ run, onCancel, cancelling = false }: { run: RunView; onCancel(): Promise<void>; cancelling?: boolean }) {
  const terminal = run.status === "completed" || run.status === "partial" || run.status === "failed" || run.status === "cancelled";
  const researched = run.coverage.assessed;
  const researchLimit = run.limits.research;
  const remaining = Math.max(researchLimit - researched, 0);
  return <section aria-labelledby="run-progress-heading" className="space-y-3 rounded-md border border-line bg-surface p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 id="run-progress-heading" className="text-base font-semibold text-fg">{statusTitle(run)}</h2><p className="text-sm text-muted">{statusDetail(run, remaining)}</p></div>{!terminal && !run.cancel_requested_at ? <button type="button" aria-label="Cancel research run" onClick={() => { void onCancel(); }} disabled={cancelling} className="rounded-md border border-line-strong px-3 py-1.5 text-sm text-fg disabled:opacity-60">{cancelling ? "Requesting cancellation…" : "Cancel research"}</button> : null}</div><div className="grid gap-2 text-sm text-fg sm:grid-cols-3"><p><span className="font-medium">{run.coverage.discovered}</span> discovered</p><p><span className="font-medium">{researched}</span> of {researchLimit} investigated</p><p><span className="font-medium">{run.shortlist.length}</span> shortlisted</p></div>{!terminal ? <><div role="progressbar" aria-label="Research completion" aria-valuemin={0} aria-valuemax={researchLimit} aria-valuenow={researched} className="h-2 overflow-hidden rounded bg-surface-2"><div className="h-full bg-accent" style={{ width: `${researchLimit ? Math.min(100, (researched / researchLimit) * 100) : 0}%` }} /></div><p className="text-xs text-muted">{remaining} companies remaining · {timeRemaining(run.started_at)}</p></> : null}{run.coverage.mechanisms.length ? <div><h3 className="text-xs font-medium uppercase text-muted">Mechanism coverage</h3><ul className="mt-1 grid gap-1 text-sm text-fg">{run.coverage.mechanisms.map((mechanism) => <li key={mechanism.mechanism_id}>{mechanism.discovered} discovered · {mechanism.selected} selected · {mechanism.assessed} investigated</li>)}</ul></div> : null}{run.coverage.gaps.length ? <div><h3 className="text-xs font-medium uppercase text-muted">Incomplete work</h3><ul className="mt-1 space-y-1 text-sm text-muted">{run.coverage.gaps.map((gap, index) => <li key={`${gap.code}:${index}`}>{gap.detail}</li>)}</ul></div> : null}</section>;
}

function statusTitle(run: RunView): string { if (run.status === "queued") return run.worker_waiting ? "Waiting for a worker" : "Research is queued"; if (run.status === "running") return "Research in progress"; if (run.status === "completed") return `${run.shortlist.length} shortlisted`; if (run.status === "partial") return "Finished with partial results"; if (run.status === "failed") return "Research stopped"; return "Cancelled"; }
function statusDetail(run: RunView, remaining: number): string { if (run.cancel_requested_at) return "Cancellation requested. Completed research remains available."; if (run.status === "queued" && run.worker_waiting) return "This campaign is waiting for a worker to pick it up."; if (run.status === "queued") return "Research will begin when a worker is available."; if (run.status === "running") return `${remaining} companies remain in the current research limit.`; if (run.status === "completed") return "Review the companies that met the brief."; if (run.status === "partial") return "Some research could not be completed. Review the available results and gaps."; if (run.status === "failed") return "The run stopped before completion. Completed research is still available."; return "The cancellation request has finished. Completed research is still available."; }
function timeRemaining(startedAt: string | null): string { if (!startedAt) return "Time remaining will appear once research starts"; const milliseconds = Math.max(0, new Date(startedAt).getTime() + 45 * 60_000 - Date.now()); const minutes = Math.ceil(milliseconds / 60_000); return minutes > 0 ? `about ${minutes} minutes remaining` : "time limit reached"; }
